"use client";

import { DocumentPreview } from "@/components/documents/DocumentPreview";
import { DownloadButton } from "@/components/documents/DownloadButton";

const mockMarkdown = `# validate_user

## Why It Exists

This function was introduced in **PR #112** to handle JWT-based authentication after the team migrated away from session-based auth.

## Key Decisions

- **JWT over sessions** — chosen for statelessness and horizontal scaling.
- **Token caching** — added in commit \`d4e5f6\` to reduce decode overhead.

## Blast Radius

Changes will directly affect \`auth.py:login\` and \`middleware.py:authenticate\`.

---

*Generated by Vortex*
`;

const mockJson = {
  function_name: "validate_user",
  why_it_exists: "Handles JWT validation introduced in PR #112.",
  key_decisions: [
    "Switched from sessions to JWT for load balancer compatibility.",
    "Added token caching for performance.",
  ],
  linked_issues: ["#42", "PR #112", "#87"],
  generated_at: "2026-03-05T00:00:00Z",
};

export default function TestPage() {
  return (
    <div className="p-6 h-screen flex flex-col gap-4">

      {/* Download button standalone */}
      <div className="flex items-center gap-3">
        <span className="font-mono text-[10px] uppercase tracking-widest text-[#6b6b6b]">
          download button
        </span>
        <DownloadButton
          filename="validate_user-decision-log"
          markdownContent={mockMarkdown}
          jsonContent={mockJson}
          onDownload={(fmt) => console.log("download pdf requested", fmt)}
        />
      </div>

      {/* Document preview with download button integrated */}
      <div className="flex-1 min-h-0">
        <DocumentPreview
          title="validate_user — Decision Log"
          functionName="validate_user"
          filepath="src/auth.py"
          primaryOwner="alice"
          generatedAt="2026-03-05T00:00:00Z"
          markdownContent={mockMarkdown}
          onDownload={() => console.log("download")}
        />
      </div>

    </div>
  );
}